server:
  grpc_port: ":50051"

database:
  dsn: postgres://postgres:postgres@localhost:5436/board_db?sslmode=disable
  max_open_conns: 10
  max_idle_conns: 5

kafka:
  brokers:
    - localhost:9092
  topic: "board-events"
  partition: 0

logging:
  level: "info"